"""Convert a single continuous GPX track to compact local-meter route geometry."""
import math
import pathlib
import sys
import xml.etree.ElementTree as ET


def convert(source, destination):
    root = ET.parse(source).getroot()
    segments = root.findall('.//{*}trkseg')
    if len(segments) != 1:
        raise ValueError('Expected one continuous track segment')
    points = []
    for p in segments[0].findall('{*}trkpt'):
        lat, lon = float(p.attrib['lat']), float(p.attrib['lon'])
        if not (-90 <= lat <= 90 and -180 <= lon <= 180):
            raise ValueError('Invalid coordinate')
        if not points or (lat, lon) != points[-1]:
            points.append((lat, lon))
    if len(points) < 2:
        raise ValueError('Track needs at least two distinct points')
    lat0, lon0 = points[0]
    scale = math.cos(math.radians(lat0))
    xy = [(math.radians(lon-lon0)*6371000*scale,
           math.radians(lat-lat0)*6371000) for lat, lon in points]
    distance = 0
    rows = []
    for i, (x, y) in enumerate(xy):
        if i:
            a, b = map(math.radians, points[i-1])
            c, d = map(math.radians, points[i])
            h = math.sin((c-a)/2)**2 + math.cos(a)*math.cos(c)*math.sin((d-b)/2)**2
            distance += 12742000*math.asin(min(1, math.sqrt(h)))
        rows.append(f'  {{{x:.4f}f, {y:.4f}f, {distance:.4f}f}},')
    pathlib.Path(destination).write_text(
        '// Generated by tools/compile_gpx.py; do not edit.\n#pragma once\n'
        'struct GpxPoint { float east, north, meters; };\n'
        f'constexpr double GPX_LAT0 = {lat0};\nconstexpr double GPX_LON0 = {lon0};\n'
        f'constexpr double GPX_LON_SCALE = {scale:.12f};\n'
        'constexpr GpxPoint GPX_POINTS[] = {\n' + '\n'.join(rows) + '\n};\n'
        'constexpr unsigned GPX_COUNT = sizeof(GPX_POINTS)/sizeof(GPX_POINTS[0]);\n'
        'constexpr float GPX_LENGTH = GPX_POINTS[GPX_COUNT-1].meters;\n')
    print(f'{len(points)} points, {distance/1609.344:.3f} miles, {distance/17.8816/60:.2f} minutes at 40 mph')


if __name__ == '__main__':
    convert(*sys.argv[1:])
