"""Bundle the same route IDs/coordinate bytes used by the iOS route library."""
from pathlib import Path
from decimal import Decimal, ROUND_HALF_UP
import math
import struct
import sys
import xml.etree.ElementTree as ET

def fnv(data):
    result=2166136261
    for byte in data: result=((result^byte)*16777619)&0xffffffff
    return result

WIDTH,HEIGHT=160,96
def rgb565(red,green,blue): return ((red>>3)<<11)|((green>>2)<<5)|(blue>>3)
PALETTE=[rgb565(*color) for color in [
    (8,24,27),(4,12,14),(18,56,51),(24,78,67),(55,75,82),(119,132,139),
    (47,94,89),(25,59,74),(91,109,112),(153,164,166),(205,216,216),
    (255,255,255),(241,245,238),(184,255,0),(105,220,86),(245,59,62)]]

def thumbnail(ident,points):
    world=1<<14
    merc=[]
    previous=None
    for lat_e7,lon_e7 in points:
        lat=max(-85.05112878,min(85.05112878,lat_e7*1e-7))*math.pi/180
        x=(lon_e7*1e-7+180)/360*world
        y=(1-math.log(math.tan(lat)+1/math.cos(lat))/math.pi)*0.5*world
        if previous is not None:
            while x-previous>world/2:x-=world
            while x-previous<-world/2:x+=world
        merc.append((x,y));previous=x
    minx,maxx=min(p[0] for p in merc),max(p[0] for p in merc)
    miny,maxy=min(p[1] for p in merc),max(p[1] for p in merc)
    spanx=max(0.00002,maxx-minx);spany=max(0.00002,maxy-miny)
    minx-=spanx*.1;maxx+=spanx*.1;miny-=spany*.1;maxy+=spany*.1
    spanx=maxx-minx;spany=maxy-miny;target=WIDTH/HEIGHT
    if spanx/spany<target:
        extra=(spany*target-spanx)/2;minx-=extra;maxx+=extra
    else:
        extra=(spanx/target-spany)/2;miny-=extra;maxy+=extra
    screen=[(round((x-minx)/(maxx-minx)*(WIDTH-1)),round((y-miny)/(maxy-miny)*(HEIGHT-1))) for x,y in merc]
    pixels=[0]*(WIDTH*HEIGHT)
    def plot(x,y,color,radius):
        for py in range(y-radius,y+radius+1):
            for px in range(x-radius,x+radius+1):
                if 0<=px<WIDTH and 0<=py<HEIGHT and (px-x)**2+(py-y)**2<=radius**2:
                    pixels[py*WIDTH+px]=color
    def line(a,b,color,radius):
        x,y=a;dx=abs(b[0]-x);sx=1 if x<b[0] else -1;dy=-abs(b[1]-y);sy=1 if y<b[1] else -1;error=dx+dy
        while True:
            plot(x,y,color,radius)
            if (x,y)==b:break
            twice=2*error
            if twice>=dy:error+=dy;x+=sx
            if twice<=dx:error+=dx;y+=sy
    for index in range(1,len(screen)):
        line(screen[index-1],screen[index],1,3);line(screen[index-1],screen[index],13,2)
    plot(*screen[0],1,6);plot(*screen[0],14,4);plot(*screen[0],15,1)
    plot(*screen[-1],1,6);plot(*screen[-1],15,4)
    packed=bytes((pixels[i]<<4)|pixels[i+1] for i in range(0,len(pixels),2))
    payload=b''.join(struct.pack('<H',c) for c in PALETTE)+packed
    return b'P1TH'+bytes([1,WIDTH,HEIGHT,16])+struct.pack('<III',ident,len(packed),fnv(payload))+payload

lines=['// Generated by tools/compile_gpx_defaults.py.','#pragma once',
       'struct GpxDefault { const char *name; uint32_t id, checksum; const gpx::Coordinate *points; uint16_t count; const uint8_t *thumbnail; uint16_t thumbnailBytes; uint32_t thumbnailChecksum; };']
entries=[]
revision=bytearray()
for index,path in enumerate(sorted(Path(sys.argv[1]).glob('*.gpx'))):
    root=ET.parse(path).getroot()
    segments=root.findall('.//{*}trkseg')
    assert len(segments)==1
    points=[]
    for p in segments[0].findall('{*}trkpt'):
        point=tuple(int((Decimal(p.attrib[key])*10_000_000).quantize(1,rounding=ROUND_HALF_UP)) for key in ['lat','lon'])
        if not points or points[-1]!=point:points.append(point)
    assert 2<=len(points)<=4096 and len(path.name.encode())<=128
    data=b''.join(struct.pack('<ii',*p) for p in points)
    ident=fnv(path.name.encode()+data) or 1
    preview=thumbnail(ident,points)
    lines.append(f'static constexpr gpx::Coordinate GPX_DEFAULT_{index}[] = {{')
    lines.extend(f'  {{{lat},{lon}}},' for lat,lon in points)
    lines.append('};')
    lines.append(f'static constexpr uint8_t GPX_DEFAULT_THUMBNAIL_{index}[] = {{')
    for start in range(0,len(preview),16):
        lines.append('  '+','.join(f'0x{b:02x}' for b in preview[start:start+16])+',')
    lines.append('};')
    preview_checksum=fnv(preview)
    entries.append(f'  {{"{path.name}",0x{ident:08x}u,0x{fnv(data):08x}u,GPX_DEFAULT_{index},{len(points)},GPX_DEFAULT_THUMBNAIL_{index},{len(preview)},0x{preview_checksum:08x}u}},')
    revision.extend(struct.pack('<III',ident,fnv(data),preview_checksum))
    print(path.name,f'{ident:08x}',len(points))
lines+=[f'static constexpr uint32_t GPX_DEFAULTS_REVISION=0x{fnv(revision):08x}u;',
        'static const GpxDefault GPX_DEFAULTS[] = {',*entries,'};']
Path(sys.argv[2]).write_text('\n'.join(lines)+'\n')
